export const LocalStorageFields = {
  _id: '_id',
  eventName: 'eventName',
  loginType: 'login_type',
  userFrom: 'user_from',
  mobileNo: 'mobile_no',
  identity: 'identity',
  profileImage: 'profile_image',
  fullName: 'full_name',
  birthdate: 'birthdate',
  gender: 'gender',
  city: 'city',
  orientation: 'orientation',
  isOrientationVisible: 'is_orientation_visible',
  hoping: 'hoping',
  educationDegree: 'digree',
  collegeName: 'college_name',
  habitsExercise: 'exercise',
  habitsSmoke: 'smoke',
  habitsMovies: 'movies',
  habitsDrink: 'drink',
  magicalPersonCommunicationStr: 'communication_stry',
  magicalPersonReceivedLove: 'recived_love',
  magicalPersonEducationLevel: 'education_level',
  magicalPersonStarSign: 'star_sign',
  likesInto: 'likes_into',
  isBlockContact: 'is_block_contact',
  latitude: 'latitude',
  longitude: 'longitude',
  radius: 'radius',
  recentPik: 'recent_pik',
  isImageUploaded: 'isImageUploaded',
  OTP: 'OTP',
  isVerified: 'isVerified',
  Token: 'Token',
  phoneNumberWithoutCode: 'phoneNumberWithoutCode',
  phoneNumberCountryCode: 'phoneNumberCountryCode',
} as const;

export type UserField = keyof typeof LocalStorageFields;
