export const LocalStorageFields = {
  _id: '_id',
  eventName: 'eventName',
  login_type: 'login_type',
  user_from: 'user_from',
  mobile_no: 'mobile_no',
  identity: 'identity',
  profile_image: 'profile_image',
  full_name: 'full_name',
  birthdate: 'birthdate',
  gender: 'gender',
  city: 'city',
  orientation: 'orientation',
  is_orientation_visible: 'is_orientation_visible',
  hoping: 'hoping',
  digree: 'digree',
  college_name: 'college_name',
  exercise: 'exercise',
  smoke: 'smoke',
  movies: 'movies',
  drink: 'drink',
  communication_stry: 'communication_stry',
  recived_love: 'recived_love',
  education_level: 'education_level',
  star_sign: 'star_sign',
  likes_into: 'likes_into',
  is_block_contact: 'is_block_contact',
  latitude: 'latitude',
  longitude: 'longitude',
  radius: 'radius',
  recent_pik: 'recent_pik',
  isImageUploaded: 'isImageUploaded',
  OTP: 'OTP',
  isVerified: 'isVerified',
  Token: 'Token',
  phoneNumberWithoutCode: 'phoneNumberWithoutCode',
  phoneNumberCountryCode: 'phoneNumberCountryCode',
} as const;

export type UserField = keyof typeof LocalStorageFields;
